language: node_js
node_js:
- stable
before_script:
- cd AppiumTests
env:
  global:
    secure: BIVjHnwwcRfD14yFgEdNL9gDQOmkd3ffYHCBvw9kn/BFPyMYj9l1yuWg5yMe6yEItbaLP/oqosl3ZwXPmkRYXvjOYeKA5dUsnpHB8iV5ptYhQOvq7eF6jA4mtiPN7dYp4DvYqlDrEJvP8qYGRXyvBK8xSlcOGhzklf26WgCC7ZVu+HeBCVgtvmuo0QfHI+P35skUd8Qj/jEAzteLy7X8maqJ+jgQWm+bjUhNbbaV6LPSp5E4z2hnDqSPnqAMSzYlKapP5F1YBqex56tGpsN2AVr/cPlwaZo4ZNZSa1ATpUoQq7jazMK3rY895qt1zFkMIFqpOctGbXJ6lpaJoNXXM18oiyXjpQkw1CbnnLRZBzJjKzmgazp3zxTzJIzNUUGoLEH+qmWaUry3F2Hm0Z4cLIF1zOu482fd1VW1oYDKZqENbQbqtzdGCTrSbTxzHoGL5Jm5c9lcO5kZjDAdRODMdRpDQq/zDIztygBidxLnrakz5LhsDLVRkWYqD3rIFJYEAlrSWu+i2tW1bYl+F9ZyrLuFlX6Cn8aOYxlE+gyIheOol7H5AmTqdcWlE3oBkHiqCwr2UYxuSe1ULaOFLE4U1D/VNpXh3OGXR1/x0cfqsLS2j7mKW/4vutp9A3uW2RCCkPyLEnSu5eKRzjRNq/tF1dGl5JOJQHlLlyLuUAfXTSo=
